#pragma once

#if !defined(PICO_XOSC_STARTUP_DELAY_MULTIPLIER)
# define PICO_XOSC_STARTUP_DELAY_MULTIPLIER 64
#endif

#define PICO_BOOT_STAGE2_CHOOSE_W25Q080 1
//#define PICO_BOOT_STAGE2_CHOOSE_GENERIC_03H 1

#if !defined(PICO_FLASH_SPI_CLKDIV)
# define PICO_FLASH_SPI_CLKDIV 4
#endif

#if !defined(PICO_FLASH_SIZE_BYTES)
# define PICO_FLASH_SIZE_BYTES (16 * 1024 * 1024)
#endif
